name: Release

on:
  push:
    tags:
      - 'v*'

env:
  STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
  EPIC_CLIENT_ID: ${{ secrets.EPIC_CLIENT_ID }}
  EPIC_CLIENT_SECRET: ${{ secrets.EPIC_CLIENT_SECRET }}
  BATTLENET_CLIENT_ID: ${{ secrets.BATTLENET_CLIENT_ID }}
  BATTLENET_CLIENT_SECRET: ${{ secrets.BATTLENET_CLIENT_SECRET }}
  IGDB_CLIENT_ID: ${{ secrets.IGDB_CLIENT_ID }}
  IGDB_CLIENT_SECRET: ${{ secrets.IGDB_CLIENT_SECRET }}

jobs:
  release:
    strategy:
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm tauri build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: GLaunch v${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/nsis/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate changelog
        id: changelog
        uses: scottbrenner/generate-changelog-action@master
        env:
          REPO: ${{ github.repository }}

      - name: Update Release Notes
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ## What's Changed
            ${{ steps.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
