name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "src-tauri"
          cache-on-failure: true

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path | tr -d '\n')" >> $GITHUB_ENV

      - name: Cache pnpm dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Get version from Cargo.toml
        id: get_version
        shell: pwsh
        run: |
          $cargoToml = Get-Content "src-tauri/Cargo.toml" -Raw
          $version = Select-String -Pattern 'version = "(.*?)"' -InputObject $cargoToml | ForEach-Object { $_.Matches.Groups[1].Value }
          echo "VERSION=$version" >> $env:GITHUB_ENV
          echo "Current version: $version"

      - name: Install dependencies
        run: pnpm install

      - name: Debug environment variables
        run: |
          echo "IGDB_CLIENT_ID length: ${#IGDB_CLIENT_ID}"
          echo "Environment variables are set: $([bool]$env:IGDB_CLIENT_ID)"
        env:
          IGDB_CLIENT_ID: ${{ secrets.IGDB_CLIENT_ID }}

      - name: Set up Tauri signing key
        run: |
          $env:TAURI_SIGNING_PRIVATE_KEY = '${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}'
          $env:TAURI_SIGNING_PRIVATE_KEY_PASSWORD = '${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}'

      - name: Build
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          EPIC_CLIENT_ID: ${{ secrets.EPIC_CLIENT_ID }}
          EPIC_CLIENT_ID_SECRET: ${{ secrets.EPIC_CLIENT_ID_SECRET }}
          BATTLENET_CLIENT_ID: ${{ secrets.BATTLENET_CLIENT_ID }}
          BATTLENET_CLIENT_SECRET: ${{ secrets.BATTLENET_CLIENT_SECRET }}
          IGDB_CLIENT_ID: ${{ secrets.IGDB_CLIENT_ID }}
          IGDB_CLIENT_SECRET: ${{ secrets.IGDB_CLIENT_SECRET }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          RUST_BACKTRACE: 1
          RUST_LOG: "debug"
        run: |
          echo "Building with IGDB_CLIENT_ID set: $([bool]$env:IGDB_CLIENT_ID)"
          pnpm tauri build

      - name: Verify version matches
        shell: pwsh
        run: |
          $tag_version = "${{ github.ref }}".Replace('refs/tags/v', '')
          $cargo_version = $env:VERSION
          if ($tag_version -ne $cargo_version) {
            Write-Error "Version mismatch! Tag version ($tag_version) does not match Cargo.toml version ($cargo_version)"
            exit 1
          }
          echo "Versions match: $cargo_version"

      - name: Generate latest.json
        shell: pwsh
        run: |
          $msiPath = Get-ChildItem "src-tauri/target/release/bundle/msi/*.msi" | Select-Object -First 1
          $signature = Get-Content "$($msiPath.FullName).sig"
          
          $json = @{
            version = "v${{ env.VERSION }}"
            notes = "Release v${{ env.VERSION }}"
            pub_date = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
            platforms = @{
              "windows-x86_64" = @{
                signature = $signature
                url = "https://github.com/Nihilop/glaunch/releases/download/v${{ env.VERSION }}/$($msiPath.Name)"
              }
            }
          }
          
          $json | ConvertTo-Json -Depth 10 | Set-Content "latest.json"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: GLaunch v${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/msi/*.sig
            latest.json
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}